### ISSUE TITLE
Allow users to disable "Approved By"

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Revisions#1010]
We could do this via "Screen Options" perhaps
![Screenshot 2023-06-20 at 2 44 33 PM](https://github.com/publishpress/PublishPress-Revisions/assets/3868028/929163ad-1a05-4ad6-bff6-7179e9cf1bd5)

**Comment by agapetry** [comment]
The Revision Archive was modified to hide the Approved by column if no rows in the current results set have an Approved By value.
