### ISSUE TITLE
Include a setting to allow / disallow post types to show in the Archive

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Revisions#1011]
Maybe we just expand on this area:

![Screenshot 2023-06-20 at 12 32 57 PM](https://github.com/publishpress/PublishPress-Revisions/assets/3868028/e182c75f-f45b-4750-acc2-eb877f6ae8be)

**Comment by agapetry** [comment]
The Revision Archive was modified to omit post types that don't save revisions.
