### ISSUE TITLE
Question about the file POT in the Revision PRO 3.5

### ISSUE THREAD

**Issue by wocmultimedia** [publishpress/PublishPress-Revisions#1053]
Hi @andergmartins , @stevejburge ,

I updated to latest 3.5  version and checking the languages folder I found out that the file pot is updated to 403 strings while other languages still have older translations. I sent you at beginning of July the updated translations files which match the file pot but you missed to update files inside the plugin folder.
Here's again the file of ES-FR-IT translations. The same files also should be set inside the Pro folder because are obsolete there too.
[ES-FR-IT_RevisionFree_TranslationUpdates_July2023.zip](https://github.com/publishpress/PublishPress-Revisions/files/12316212/ES-FR-IT_RevisionFree_TranslationUpdates_July2023.zip)

Thanks,
Angelo

**Comment by agapetry** [comment]
Sorry @wocmultimedia and @stevejburge, this had to fall through the cracks to keep other changes in view for the 3.5 release. I will catch up on the language files in the next minor release and adhere to the update policy moving forward.
