### ISSUE TITLE
The footer is broken

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Revisions#1112]
<img width="661" alt="Screenshot 2023-10-19 at 8 23 50 AM" src="https://github.com/publishpress/PublishPress-Revisions/assets/3868028/7fc8eddb-0e47-4125-9f3f-c9a61211c7d9">

**Comment by agapetry** [comment]
@stevejburge Is the issue that there's not enough top margin above the footer?

**Comment by stevejburge** [comment]
@agapetry Yes, it's a margin issue

Archive screen:
![Screenshot 2023-10-23 at 9 08 34 AM](https://github.com/publishpress/PublishPress-Revisions/assets/3868028/b6adf882-9f31-448c-bdf3-1dafef1ec040)

Queue screen:
![Screenshot 2023-10-23 at 9 08 53 AM](https://github.com/publishpress/PublishPress-Revisions/assets/3868028/b41c85ff-d8e6-4eb0-adad-1e9a31f347c2)
