### ISSUE TITLE
Queue, Archive pages use paging option from Pages screen

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Revisions#1113]
![Screenshot 2023-10-19 at 8 28 24 AM](https://github.com/publishpress/PublishPress-Revisions/assets/3868028/cf015ed9-43e3-4947-9882-9f13e077895b)

**Comment by agapetry** [comment]
Paging default to 20 items per page on both Revision Queue and Revision Archive, but that "per page" setting is not currently adjustable. Do you want me to add Screen Options functionality for this next release?

**Comment by stevejburge** [comment]
@agapetry You can see the issue on the PublishPress.com site: /wp-admin/admin.php?page=revisionary-archive

There's 2300+ revisions, but no way to get to the 2nd page:

![Screenshot 2023-10-23 at 9 06 15 AM](https://github.com/publishpress/PublishPress-Revisions/assets/3868028/dace3595-552b-4236-8b9b-9f401b58bc35)
