### ISSUE TITLE
Approve Button missing in Gutenberg v17

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Revisions#1142]
![image](https://github.com/publishpress/PublishPress-Revisions/assets/83811723/3d02a38c-3559-4e9d-b4a0-cd859b932ba5)

No Approve button on latest version of Gutenberg: https://wordpress.org/plugins/gutenberg/

**Comment by agapetry** [comment]
This is caused by the lack of any date display by Gutenberg 17.
