### ISSUE TITLE
Jet Engine: Users still able to approve revisions on CPT 

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Revisions#1154]
ISSUE:

Users still being able to Approve Revisions even when they dont have edit_published capabilities for CPT from Jet Engine

![image](https://github.com/publishpress/PublishPress-Revisions/assets/83811723/40962eb2-34df-4438-9f7e-f9322a8b248f)
![image](https://github.com/publishpress/PublishPress-Revisions/assets/83811723/15838d4d-0cc0-4a88-9585-edacafc5ba2c)

So far this only happens for CPT coming from Jet Engine.

Works fine on default post type or cpt from CPT UI plugin.

Jet Engine Plugin: https://rambleventures.slack.com/files/U03SRCBBFUZ/F06DJH11A8L/jet-engine.zip

https://secure.helpscout.net/conversation/2474971128/218458?viewId=6932143

**Comment by agapetry** [comment]
@rizaardiyanto1412 @bjoernzosel  I'm not able to replicate this issue using the current plugin releases.  I tried with two different configurations:

* JetEngine post type has a distinct capability type value defined in Post Type settings 
* JetEngine post type is defined without specifying a capability type, but is enabled for "Unique Post Type Capabilities" on the PublishPress Capabilities screen

In both cases, the Revisor cannot approve their own revision.

**Comment by rizaardiyanto1412** [comment]
@agapetry I confirm this is not an issue anymore in the latest plugin release. I think we could close this issue for now.
