### ISSUE TITLE
Submit Revisions Disabled If Date is Future on Classic Editor

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Revisions#1157]
ISSUE: Cant submit revisions if scheduled for future date (Classic editor)

Step to replicate:

1. PublishPress Revisions + Classic editor
2. Create new revisions
3. Change the published date to the future
4. Observe issue, submit will not showing

![image](https://github.com/publishpress/PublishPress-Revisions/assets/83811723/e476be82-c754-4137-87e5-000eff34b2d8)

**Comment by agapetry** [comment]
After testing out this issue, I'm seeing that Revisions cannot be submitted immediately after selecting a future date in Classic Editor, but can be submitted after saving the new date selection ("Update Revision" button). Is that a sufficient workaround for you?

The development issue I face is that the Classic Editor autosave operation does not capture an unsaved date selection, so enabling submission prior to update would cause that date selection to be lost.
