### ISSUE TITLE
comment_count not being set on WordPress VIP

### ISSUE THREAD

**Issue by darylldoyle** [publishpress/PublishPress-Revisions#1161]
On WordPress VIP, I'm running into an issue where updating the `comment_count` field is failing, and it's being stored as `0`. This, in turn, is causing the revisions to become orphans in the database and unable to be accessed. I assume it's likely because VIP utilises ElasticSearch under the hood, and the adapter isn't allowing direct writes to that field.

The lines below are where this is failing specifically.

https://github.com/publishpress/PublishPress-Revisions/blob/72c368e380ed36d589d4843ea33dad200ba261c9/revision-creation_rvy.php#L179-L183

I've managed to work around this by utilising the `pre_wp_update_comment_count_now` to force WP to update the comment count for us. This means the update goes through all the correct adapters. The code looks like this:

```php
$update_data = ('pending-revision' == $data['post_mime_type'])  //
? ['comment_count' => $main_post_id, 'post_modified_gmt' => $data['post_modified_gmt'], 'post_modified' => $data['post_modified']]
: ['comment_count' => $main_post_id];

$wpdb->update($wpdb->posts, $update_data, ['ID' => $revision_id]);

// Hack WP into updating the comment count to store the main post ID in the comment_count field.
add_filter(
	'pre_wp_update_comment_count_now',
	function( $new, $old, $post_id ) use ( $revision_id, $main_post_id ) {
		if ( (int) $revision_id === (int) $post_id ) {
			return $main_post_id;
		}

		return $new;
    },
    10,
    3
);

// Update the comment count.
wp_update_comment_count_now( $revision_id );
```

I've confirmed that this works, but it's mostly duplicating what's happening above. I wonder if you'd want to include this in the core plugin (it may be better for compatibility?). If not, it'd be great to have an action that we could hook into to run this code without having to edit the plugin files.

The `revisionary_new_revision` doesn't pass through the `$main_post_id` which would be required.

Something like the below would work:

```php
/**
 * Fired when a new revision is being inserted into the database.
 *
 * @param int   $revision_id  The ID of the inserted revision.
 * @param int   $main_post_id The ID of the published post for this revision.
 * @param array $data         The post data used to create this revision.
 */
do_action( 'revisionary_new_revision_inserting', $revision_id, $main_post_id, $data );
```

This would need to be fired after the `comment_count` update is called.

**Comment by agapetry** [comment]
Thanks for the detailed report and code snippets, @darylldoyle.

I can add the new action you suggest and also force the comment_count update by default, with a plugin hook to suppress that behavior in case different treatment is needed.
