### ISSUE TITLE
List view of pending revisions other’s submitted to your post. 

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Revisions#12]
> While in wp-admin I can view posts > pending, the problem is that if I’m logged in as an admin I’ll see potentially hundreds or thousands of pending posts. This means pending revisions on my posts are unfindable. There is no filter for “my posts” or “pending to my post” when viewing “posts > pending”.

As with this issue, best to solve with a tab in "Revisions Queue"?
https://github.com/publishpress/Revisionary/issues/11

**Comment by Drumbell** [comment]
This PR can be marked as resolved. A Fantastic addition.

**Comment by stevejburge** [comment]
Solved in 2.0
