### ISSUE TITLE
Add support for CPT in Revisions Archive 

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Revisions#1216]
Currently Revisions Archive only support for Post and Pages.

Can we add a support for CPT as well?

**Comment by stevejburge** [comment]
@rizaardiyanto1412 Can you share more details on this? CPTs are supported

**Comment by rizaardiyanto1412** [comment]
@stevejburge Actually Revisions Archive only showing for Post and Pages post type only. I've tested this
![image](https://github.com/publishpress/PublishPress-Revisions/assets/83811723/02f36d17-e25c-4af6-8bef-7ec7837683af)

**Comment by stevejburge** [comment]
@rizaardiyanto1412 Do these other post types definitely have revisions enabled?

**Comment by rizaardiyanto1412** [comment]
![image](https://github.com/publishpress/PublishPress-Revisions/assets/83811723/165f23e9-1542-4d59-a4af-88f9dcb84f03)
Yup it does @stevejburge 

Original report: https://secure.helpscout.net/conversation/2577666771/221972?viewId=6932143

**Comment by rizaardiyanto1412** [comment]
This is wrong report. Revisions archive is support for custom post type, however there are some requirements in order for the CPT to show.

Here is more details from Kevin

- The post type must have Revisions enabled as a feature. In other words, it must be configured to save revisions; Revision Archive will only show what already exists.
- The post type must be using the standard WordPress mechanism for revision storage
- Normally, it must either be registered as a public post type, or it must use a distinct editing capability (not edit_posts or edit_pages)
- In addition, the following post types are explicitly included: WooCommerce Products and Orders, The Events Calendar Events
- The following post types are excluded: Attachments (Media), Nav Menus, Nav Menu Items, Blocks, Templates, Template Parts, Custom CSS, Customize Changesets, Global Styles, TablePress Tables, ACF Fields and Field Groups, WooCommerce Refunds and Product Variations
- The "revisionary_archive_post_types" filter is applied, allowing custom code snippets to enable other post types for inclusion in Revision Archive. Note that post types included in this way may not behave as expected for previewing, editing or comparison.
