### ISSUE TITLE
Add support for WooCommerce Membership

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Revisions#1268]
When create new revisions on WooCommerce membership plan, the post data is empty. 

Can we add compat with WooCommerce Membership

Original product:
![image](https://github.com/publishpress/PublishPress-Revisions/assets/83811723/d51691e6-65eb-46a5-94b9-37b54b0876c0)

When create new revisions:

![image](https://github.com/publishpress/PublishPress-Revisions/assets/83811723/d0ad91ed-8b29-43a4-a4c9-34e590d7e496)

Woo Membership plugin: https://rambleventures.slack.com/files/U03SRCBBFUZ/F074B0DFZ0U/woocommerce-memberships.zip

**Comment by agapetry** [comment]
I reviewed the WooCommerce Membership code and found that it is storing much of the Membership Plan data into a single array in the options table.  The option_name is wc_memberships_rules

Given that third party schema, it is not feasible for our plugin to support the submission and approval of Membership Plan revisions.  I suggest contacting WooCommerce Membership support (SkyVerge) and asking them to migrate the Membership Plan storage to use the postmeta table for better plugin compatibility.
