### ISSUE TITLE
Code Errors in File wp-content/plugins/publishpress-revisions-pro/lib/vendor/publishpress/publishpress-revisions/functions.php

### ISSUE THREAD

**Issue by yjfnyc** [publishpress/PublishPress-Revisions#1307]
## Steps to Reproduce (for bugs)

1. Just look at the file on line 219 and line 240, the function call `array_value` is no where to be found. They should be `array_values` instead.
<img width="1708" alt="Screenshot 2024-07-02 at 4 18 57 PM" src="https://github.com/publishpress/PublishPress-Revisions/assets/9726273/6fdf1d61-9b7e-4090-8a47-2dca0d46c035">

2.
3.
4.

## Your Environment

* Version used: "publishpress/publishpress-revisions-pro": "3.5.11",
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by agapetry** [comment]
@yjfnyc Good catch, but I wonder about your use case because the function argument which causes that code to execute is never passed by the plugin. I will include the fix in the next release.
