### ISSUE TITLE
Duplication of empty ACF items when editing revisions with ACF Flexible Content in PRO version 3.5.9

### ISSUE THREAD

**Issue by ThiagoBrunoPereira** [publishpress/PublishPress-Revisions#1324]
I’m encountering an issue with the PRO version 3.5.9 of the plugin. When I edit a revision and add new items within the ACF Flexible Content field on a page, after updating the revision, the same ACF items (but empty) are duplicated in the published post.

I tested the same operation with the non-PRO version of the plugin, and this behavior does not occur. I also noticed significant differences in the files between the PRO and free versions when compared after downloading.

Even after updating to the latest PRO version (3.5.11), the issue persists.

**Comment by stevejburge** [comment]
Hi @ThiagoBrunoPereira. Thanks for using PublishPress. As a Pro-user, please open a support ticket on our site. You'll get much faster help than here on Github.
