### ISSUE TITLE
Revision creation fails with obscure error message under some conditions

### ISSUE THREAD

**Issue by micahshu** [publishpress/PublishPress-Revisions#1364]
## Expected Behavior
Under the wp pages tab when clicking "New Revision" button it should create a new revision for this page

## Current Behavior

On certain pages when the button is clicked it redirects us to a page will only the text "No revision specified."

## Possible Solution

Unknown, currently we can open a revision for the page by going through the page editor sidebar

## Steps to Reproduce (for bugs)

1. Open the wordpress pages tab
2. Hover over specific page
3. Click "New Revision" button
4. "No Revision specified"

## Context

We are unable to create new revisions for pages through this method, and have to open the page to edit and enable a revision through that page
## Your Environment

Wordpress 6.6.1
Revision Version 3.5.13\
Beaver Builder Theme Version: 1.7.16 (using child theme)

**Comment by agapetry** [comment]
@micahshu This result was likely caused by an issue in the "limit to one revision" mechanism, but Revisions 3.5.14 and earlier did not display a meaningful error message. Please retry with Revisions 3.5.15 (just released).
