### ISSUE TITLE
Update author and / or publish date?

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Revisions#16]
Good question from a tester:

> is the published date of a revision not supposed to be updated on the post after it is published? Because I noticed, After publishing a revision, it updates the author to the last revisor of the post but keeps the original publish date of the post

![published](https://user-images.githubusercontent.com/3868028/64990620-22b17b80-d89e-11e9-8cda-60f06e1638d4.jpg)
![Pending](https://user-images.githubusercontent.com/3868028/64990621-234a1200-d89e-11e9-962c-9a5b577956c0.jpg)
![Before](https://user-images.githubusercontent.com/3868028/64990623-234a1200-d89e-11e9-90c9-f0fc07f74e07.jpg)

**Comment by agapetry** [comment]
This option was added in version 2.4:

![image](https://user-images.githubusercontent.com/43488774/139502682-72d4cdcc-f33f-45f4-9d98-5bf1cb2d0e1c.png)
