### ISSUE TITLE
Some small formatting issues with the Revisionary table headers

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Revisions#18]
On smaller screens, the headings get squashed up at an angle:

![rev-table](https://user-images.githubusercontent.com/3868028/65878485-2d6b1680-e35c-11e9-874b-6304f6fde19d.png)

**Comment by agapetry** [comment]
I'd be interested in hearing what our CSS experts have to say about this.  The longest headings get pushed up when the sorting indicator (little black arrow) gets crowded down to the next line. (Yes, it's still there, just hidden).  The same thing happens on the WP screens (Users, Posts, Pages) if plugins have added enough custom columns.

I guess if push came to shove, we could make the Post Author column removable.

**Comment by agapetry** [comment]
@stevejburge Based on a look at the current version, this was resolved:

![image](https://github.com/publishpress/PublishPress-Revisions/assets/43488774/deb8beba-5cff-497b-988e-20024d4b7df4)
