### ISSUE TITLE
Pro: Error message when using Quick Edit:

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Revisions#181]
It looks like you can't use the Quick Edit feature if a revision is pending for unpublished content:

<img width="1245" alt="Screen Shot 2020-10-02 at 4 48 17 PM" src="https://user-images.githubusercontent.com/3868028/94970200-211b1b80-04d2-11eb-9a80-4142e1bd94b1.png">

**Comment by agapetry** [comment]
@stevejburge I can't replicate this with the current version. The message in the screen capture was from the old revision submission mechanism prior to version 3.0; I'm pretty sure this error can't occur now.
