### ISSUE TITLE
"Submit to" Dropdown for Revision Edit

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Revisions#201]
Related to https://github.com/publishpress/PublishPress-Revisions/issues/199

People may understand "Copy" better than "Revise" or "Revision".

I'm on the fence about this. "Revisions" does match up with our plugin name. 

But "Copy" is a term that is probably understood by a lot more users than "Revision".

**Comment by DaringDreams** [comment]
"Copy post as Revision" is simple, accurate, and matches the name. It simply means we are copying the post and setting it as a revision. Speak it out loud:
_I'd like to make corrections to our staff meeting article. Don't have time to finalize for publishing. I'll copy post as revision._

![Revision message](https://user-images.githubusercontent.com/4361528/96805840-6347c680-13c7-11eb-9c45-cb2101e6f43e.png)

If we wanted it slightly fancier it could be "Copy post as a Revision" with our existing hover text for further explanation. Even with adding the word "a" it uses less space than "Save as Pending Revision".

**Comment by agapetry** [comment]
Soon with the workflow statuses support, there will be a need to distinguish between:

- submitting a revision for approval
- creating a revision (for further editing prior to submission)

I think we'll need something more like a dropdown select.

**Comment by stevejburge** [comment]
@agapetry Agreed. I think we need to think a little bigger and take more control of the "Publish" metabox (or replace it)

**Comment by DaringDreams** [comment]
Indeed those are good things. Drafted up a more organized metabox layout that allows selecting:
    submitting a revision for approval
    creating a revision (for further editing prior to submission)

![dropdown](https://user-images.githubusercontent.com/4361528/97051637-5c8a9200-1534-11eb-85eb-e63d4ccb8f3b.png)

Simplified the wording to identify who the post is going to. When no revision option is selected it would look like:

![Metabox](https://user-images.githubusercontent.com/4361528/97050216-d4a38880-1531-11eb-99eb-21135e90b8df.png)

Clicking the "Submit to" checkbox could have the "Publish" button change to a "Save" button. This way it's crystal clear that we are no longer publishing the post on your screen but are saving it for later (whether for approval or further editing purposes).

**Comment by DaringDreams** [comment]
If we went the [Save as ](https://github.com/publishpress/PublishPress-Revisions/issues/199#issuecomment-715621867)route the buttons could be even more uniformed:

![TinyMCE](https://user-images.githubusercontent.com/4361528/97061083-5f907d00-154a-11eb-9305-d02a17bd3b34.png)

The "Save as" button could utilize similar dropdown styling to be consistent and informative just like Gutenberg.

**Comment by stevejburge** [comment]
@agapetry I think there may be sense in this? We move all key settings into the "Publish" box?

The button in the top toolbar simply says "Publish", "Save", "Update" etc

**Comment by agapetry** [comment]
We decided in favor of Revision terminology, but with an option to use "Working Copy" / "Change Request" labels instead.

Some of these UI ideas could be revisited in our revision statuses / workflow development.
