### ISSUE TITLE
UI for the Pre-publish checks area

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Revisions#22]
This UI is a little clunky:
<img width="284" alt="Screen Shot 2019-10-08 at 3 35 37 PM" src="https://user-images.githubusercontent.com/3868028/66427117-5b49fe00-e9e1-11e9-95b8-d04aaf9ea155.png">

**Comment by Drumbell** [comment]
For Gutenberg I suggest:

![Save a Revision](https://user-images.githubusercontent.com/4361528/66513988-20070800-ea91-11e9-9fe6-4a722b675932.png)

For Classic Editor:

![Save Revision](https://user-images.githubusercontent.com/4361528/66514008-2c8b6080-ea91-11e9-9339-8560a825e96f.png)

"Save a Revision" as a button is concise while letting the user know exactly what it does along with adding the current hover message.

**Comment by stevejburge** [comment]
Thanks @Drumbell 

The alternative might be to move it down below the bottom "Publish" box

![66427117-5b49fe00-e9e1-11e9-95b8-d04aaf9ea155](https://user-images.githubusercontent.com/3868028/66519542-8271ff80-eab5-11e9-9850-4cce681b855b.png)

**Comment by Drumbell** [comment]
The problem with moving "Save a Revision" below the other boxes is that not only is it hidden, but starts to become disorganized. As long as the revision button has a medium grey like the picture above it won't distract the submitter from the "Update/Publish" action button. Having similar buttons next to each other is a good thing as long as it doesn't become cluttered.
