### ISSUE TITLE
The Events Calendar produces "That page can’t be found" on preview

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Revisions#26]
One small issue with "The Events Calendar" integration.

Each new revision gets an extra number in the URL ... -2, -3 and son

<img width="355" alt="Screen Shot 2019-10-15 at 9 48 06 AM" src="https://user-images.githubusercontent.com/3868028/66837579-38fc3700-ef31-11e9-9846-29a4072485cf.png">

<img width="446" alt="Screen Shot 2019-10-15 at 9 49 11 AM" src="https://user-images.githubusercontent.com/3868028/66837513-21bd4980-ef31-11e9-86b8-3eec8e00fcfa.png">

Following the link leads to "Oops! That page can’t be found."

**Comment by stevejburge** [comment]
Same thing happens with WooCommerce products too

<img width="413" alt="Screen Shot 2019-10-15 at 10 15 51 AM" src="https://user-images.githubusercontent.com/3868028/66839710-d86ef900-ef34-11e9-9576-96e3206a98d6.png">

**Comment by stevejburge** [comment]
Oddly, I can't recreate it. Closing for now

**Comment by agapetry** [comment]
There is an irregularity here.  Other post types get an ID-based preview url, which will redirect to the published post with top bar "This is the Current Revision."  I'll look into making TEC event previews work that way too.

**Comment by agapetry** [comment]
Forcing an ID-based preview URL looks like a no-go since TEC (and likely other plugins) use the custom url arguments to trigger plugin involvement.
