### ISSUE TITLE
Post-publishing success message

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Revisions#33]
On the frontend, when you click "Publish Now: there's no success message. You're just redirected to the published post.

Maybe we should show a success message in the green menu bar.

**Comment by Drumbell** [comment]
Good idea. The text string could say "Changes have been saved" or for simplicity "Changes saved". While saying something is successful works; stating what has happened (without the word "successful") lets one know that publishing was successful. Adding the word "successful" in this situation is redundant. Stating "Changes saved" says the what and it's state while being crystal clear on what it means.

**Comment by stevejburge** [comment]
Closing in favor of https://github.com/publishpress/PublishPress-Revisions/issues/196
