### ISSUE TITLE
New featured image in revision doesn't apply when publishing

### ISSUE THREAD

**Issue by carbonduck** [publishpress/PublishPress-Revisions#351]
My WP workflow with revisions:

1. Revise the post content
2. Sometimes change the featured image
3. Schedule the revision for a future date/time

But when the revision goes live, the new featured image does not get applied. Instead, the existing featured image gets removed, **resulting in a post with no featured image at all.**

**Comment by stevejburge** [comment]
Hi @carbonduck 

Sorry, Github isn't a good place for bug report unless they're very specific and include code.

Can you open a support ticket on our site, and include your Site Health information?
