### ISSUE TITLE
Option to Publish and Save a Revision

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Revisions#38]
We have a user who want to use revisions as a kind of backup option

> I want a setting to "allow" direct publishing + storing the revision. With this, there is no "checkbox" in publishing options (in a way, it is checked by default and hidden) - the post is published on saving and also a copy of its revision.

To do this, we'd need our own log https://github.com/publishpress/PublishPress-Revisions/issues/25

**Comment by agapetry** [comment]
@stevejburge Closing because the described behavior is actually the normal functionality of an Editor. I think Revision Archive is what they were missing.
