### ISSUE TITLE
post_content_filtered column content lost

### ISSUE THREAD

**Issue by swissspidy** [publishpress/PublishPress-Revisions#412]
Google's [Web Stories WordPress plugin](https://wordpress.org/plugins/web-stories/) makes heavy use of the `post_content_filtered` column.

We've [learned](https://wordpress.org/support/topic/after-updating-stories-content-is-lost-in-backend-still-shows-in-frontend/page/2/#post-14460732) that PublishPress Revisions doesn't always preserve data stored in `post_content_filtered`, which leads to data loss when creating stories.

Always preserving that column (while keeping the special case for Jetpack's Markdown feature) should help solve the problem.

**Comment by agapetry** [comment]
@swissspidy Please let me know if this PR resolves your issue. If not, I'm glad to dig further.
