### ISSUE TITLE
Revised by in Revision Queue is incorrect

### ISSUE THREAD

**Issue by rforster-dev** [publishpress/PublishPress-Revisions#466]
When creating a revision of a post, when you go to the revision queue, it will _sometimes_ be correct, but a refresh of the page, will then change it to be the same as the original Author of the post?

To reproduce...

1. Create a post logged in as 1 account.
2. Log out
3. Log in with a _different_ account
4. Edit the post, and create a revision of it
5. View the revision queue

**What should happen**
I should see that the "Revised By" column is who created the Revision

**What actually happens**
It changes back to the original Author of the post, which is incorrect.

**Comment by agapetry** [comment]
@stevejburge We should revisit this to see if it still occurs with 3.0

**Comment by stevejburge** [comment]
Yes, many of these bugs may be out-of-date with 3.0
