### ISSUE TITLE
Design touches for "New working copy" feature

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Revisions#467]
![Screen Shot 2021-09-17 at 13 10 24](https://user-images.githubusercontent.com/4999794/133834741-c56dc18e-ef98-4d75-8b1e-c15abcd34224.png)

**Comment by htmgarcia** [comment]
@stevejburge elements updated to use WP UI
![Screen Shot 2021-09-21 at 14 31 27](https://user-images.githubusercontent.com/4999794/134235912-bb63cc57-dd99-487d-9bad-271e9831bb63.png)
![Screen Shot 2021-09-21 at 14 31 34](https://user-images.githubusercontent.com/4999794/134235913-93472608-fadb-4101-8068-5288c32b29b8.png)
![Screen Shot 2021-09-21 at 14 31 43](https://user-images.githubusercontent.com/4999794/134235917-8ce337f5-85d2-49a7-988f-31610561566b.png)

**Comment by stevejburge** [comment]
Thanks @htmgarcia, that's definitely better

- I wonder if we can make the View / Appprove link stand out more

- Should we use left align for Status and Publish? Here's the WP default:

<img width="269" alt="Screen Shot 2021-09-22 at 10 31 47 AM" src="https://user-images.githubusercontent.com/3868028/134363517-acd56803-df83-4cdc-bf2a-ccf308c44b8f.png">

**Comment by htmgarcia** [comment]
@stevejburge the view/approve tweak . The status and publish alignment seems to follow the style from core
 ![Screen Shot 2021-09-23 at 13 36 49](https://user-images.githubusercontent.com/4999794/134564705-90a46f05-ce9a-46c1-99c2-2979748cc4d4.png)

**Comment by stevejburge** [comment]
@htmgarcia Thanks. That looks clearer. I wonder if we should consider using PublishPress purple for the buttons?

**Comment by htmgarcia** [comment]
@stevejburge preview:
![Screen Shot 2021-09-24 at 11 26 17](https://user-images.githubusercontent.com/4999794/134709596-217f2d56-3de0-4108-ad04-76c71ba5710a.png)

**Comment by stevejburge** [comment]
Yes, or even solid purple for both? This is the normal "Publish"

<img width="283" alt="Screen Shot 2021-09-24 at 12 34 01 PM" src="https://user-images.githubusercontent.com/3868028/134710055-da3b8a7e-6484-45f6-a7ae-e26c833f69d7.png">

**Comment by htmgarcia** [comment]
@stevejburge update
![Screen Shot 2021-09-24 at 14 30 57](https://user-images.githubusercontent.com/4999794/134730452-82120d04-d3ab-42e6-ab2e-2ffbfe0ac8f0.png)

**Comment by stevejburge** [comment]
@htmgarcia thanks. I think that's worth trying. @agapetry?

**Comment by htmgarcia** [comment]
@agapetry changes comparison https://github.com/publishpress/PublishPress-Revisions/compare/development-3.0...ppr-467
If I missed to style other elements, please let me know.

btw, not a big deal but is possible to change the `<button>` that wraps `<a>` tags (and vice versa) for `<div>`? I tried myself but that broke some functionality. As example: https://github.com/publishpress/PublishPress-Revisions/blob/ppr-467/admin/rvy_post-block-edit.dev.js#L50-L52

**Comment by agapetry** [comment]
I'm still concerned that gives the impression that clicking "View / Approve" completes an approval, but if you guys want to go with it, I won't object.

**Comment by stevejburge** [comment]
@agapetry Yes, I'm unsure about this UI still. I wonder if there is better wording we can add?

Or maybe an "eye" icon on the top button and "check" icon on the right button?

**Comment by htmgarcia** [comment]
@stevejburge @agapetry icon support + different button styles for "View / Approve"
![Screen Shot 2021-09-24 at 17 00 49](https://user-images.githubusercontent.com/4999794/134744208-d28aab1e-f140-4f53-94fe-88f898ed00f0.png)
![Screen Shot 2021-09-24 at 17 03 01](https://user-images.githubusercontent.com/4999794/134744210-d9c1e6ed-84d5-4a41-bd7a-a877b32f3cfb.png)

**Comment by htmgarcia** [comment]
@stevejburge which option?

**Comment by stevejburge** [comment]
for me, I prefer the two purples

**Comment by agapetry** [comment]
Okay, since you asked... 

The checkbox on the Submit button seems okay, though possibly unnecessary.

For "View / Approve" I prefer the white button (because it's not a primary action) and no icon (because the eyeball feels somewhere on the odd / creepy gradient).

**Comment by agapetry** [comment]
@stevejburge How would you feel about this alternative?

![image](https://user-images.githubusercontent.com/43488774/135355733-eb528758-1626-4ea5-bfae-d5784555efbd.png)

Testing this current PR made me realize the main problem with a primary-looking View / Approve button comes when Gutenberg auto-flips the sidebar panel from Page to Block.  At that point, View / Approve looks like the only action button available and it's not clear that no action is applied unless chosen on the View screen.

**Comment by stevejburge** [comment]
My first thought is “too subtle for such a key link”

**Comment by agapetry** [comment]
How about this:

![image](https://user-images.githubusercontent.com/43488774/135373186-2dcaee0e-d33b-419d-8b2a-a89cd85ec551.png)

![image](https://user-images.githubusercontent.com/43488774/135375335-43760ebc-1228-42f9-a335-04e662680d1d.png)

It restores the top-level clue about the special preview functionality, but eliminates the ambiguity of two similar button captions side by side.  Then the different purposes of the two preview modes are clearly stated in the dropdown without perpetually cluttering the main screen.

**Comment by stevejburge** [comment]
@agapetry Thanks. Yes, this is clearer. 

@htmgarcia Ideally all 3 buttons will have PublishPress style, please. So "Update Revision" should be obviously a PublishPress button too

**Comment by htmgarcia** [comment]
@stevejburge all set for the 3 purple buttons
![Screen Shot 2021-09-30 at 10 31 31](https://user-images.githubusercontent.com/4999794/135485740-f84052a4-32db-4692-b10a-43b6aac027ba.png)

**Comment by htmgarcia** [comment]
Sorry the "Update revision" style has been corrected.
![Screen Shot 2021-09-30 at 10 41 50](https://user-images.githubusercontent.com/4999794/135487503-dcce292c-489f-4d3f-b86c-732d0a2fd7ad.png)

**Comment by stevejburge** [comment]
Thank @htmgarcia. I think that first one looks best, particularly if we can remove the default blue "Preview" https://github.com/publishpress/PublishPress-Revisions/issues/467#issuecomment-931437881

**Comment by htmgarcia** [comment]
@stevejburge fixed. I think @agapetry will handle the blue "Preview".

**Comment by agapetry** [comment]
@stevejburge For comparison, here's how Update Revision would look with primary styling:

![image](https://user-images.githubusercontent.com/43488774/135484636-0e69f5e9-b007-478b-abd2-a6fca327b6ce.png)
