### ISSUE TITLE
Fix the Notice on Install

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Revisions#483]
This notification is looking a little old and not very useful
![Screen Shot 2021-10-13 at 10 49 56 AM](https://user-images.githubusercontent.com/3868028/137157668-1ac1139c-95e2-4788-a4c6-7780cfea1f7f.png)
:

**Comment by agapetry** [comment]
The Revisions 3.0 release will disable the welcome message until we establish an updated one.
