### ISSUE TITLE
Revision submission clears WordPress homepage setting (Settings > Reading)

### ISSUE THREAD

**Issue by Rainville14** [publishpress/PublishPress-Revisions#493]
I made pending revisions to the page that was set to the homepage. I then deleted the revision. When I did that, it triggered that the Homepage was deleted and defaulted the homepage to "Your latest post" and displayed the Blog as the homepage.

**Comment by stevejburge** [comment]
Hi @Rainville14 

Github is for not questions about your personal site, but for bugs that can be replicated and for discussion about code solutions.

- Can you give us a step-by-step guide so we can re-create the issue, please. 
- If you have code to share, or anything to report in your error log, please do share

**Comment by Rainville14** [comment]
1. Set homepage in Appearance > Customize > Homepage Settings to a static page
2. Make update to page that is set as homepage
2. Check checkbox for "Save as Pending Revision"
3. Click Update
4. Go to Revision Queue
5. Click Delete to delete the revision (which should only remove the revision)
6. Verify in Appearance > Customize > Homepage Settings that it is no longer set to the Static Page as it was before. In my case it was changed to "Your latest posts"

**Comment by stevejburge** [comment]
@agapetry A similar report here:
https://wordpress.org/support/topic/homepage-removed-when-revising-it/

I can confirm in testing:
<img width="490" alt="Screen Shot 2021-11-10 at 2 45 12 PM" src="https://user-images.githubusercontent.com/3868028/141182527-7a598ad1-8570-40a5-99a9-7ab02a64d332.png">
