### ISSUE TITLE
Gutenberg plugin: generic error screen error appears when submitting revision in 3.0

### ISSUE THREAD

**Issue by skorasaurus** [publishpress/PublishPress-Revisions#508]
Hi, 

Upon upgrading to Publishpress Revisions 3.0 (free version); users with the revisor role receive the gutenberg error "the editor has encountered an unexpected error" modal when submitting a revision to an already published post. 

I have only experienced this error after I upgraded to 3.0 of the plugin. 

I am able to reproduce this on a vanilla wordpress site with no plugins installed except gutenberg 11.8.3 and publishpress revisions 3.0 and default settings of the plugin. 

Note: the revised post is listed at http://case.test/wp-admin/admin.php?page=revisionary-q&post_status=draft-revision ; 
as shown in the screenshot below

![image](https://user-images.githubusercontent.com/955351/141157045-766e60a1-9fdd-4bca-9b45-e97de2a73d52.png)

To reproduce: 
1. (if necessary, create vanilla wordpress site) 
2. (if necessary, create and publish a new post with post title and post content, any block content should be fine) 
3. install  `wp plugin install revisionary --activate` to version 3.0. 
4. create new user who has role of revisor ; e.g. `wp user create laura nul2l@null.com  --role=revisor`
5. login as new user; 
6. go to a published post, click new revision in top toolbar
7. add block content
8. clicking the 'update revision' button as shown in image below 
![image](https://user-images.githubusercontent.com/955351/141157840-db8b78b9-b144-4017-8416-2032bdd325de.png)

"the editor has encountered an unexpected error" in gutenberg appears. 
![image](https://user-images.githubusercontent.com/955351/141157920-e1536492-11b4-4d31-a024-2b9906e63c86.png)

The output from the browser console and from clicking 'copy error' in the gutenberg error screen are available at https://gist.github.com/skorasaurus/a1aadae9f523a5d4815bda915c9550c2

**Comment by stevejburge** [comment]
@agapetry Can confirm in my testing

```
bf@http://november-9.local/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:150:474
bf@http://november-9.local/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:151:43
bf@http://november-9.local/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:151:43
Vh@http://november-9.local/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:149:471
Qj@http://november-9.local/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:173:497
unstable_runWithPriority@http://november-9.local/wp-content/plugins/gutenberg/vendor/react.min.755b0ae9.js:24:26
Za@http://november-9.local/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:8
eb@http://november-9.local/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:170:165
gf@http://november-9.local/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:162:319
$g/<@http://november-9.local/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:230
unstable_runWithPriority@http://november-9.local/wp-content/plugins/gutenberg/vendor/react.min.755b0ae9.js:24:26
Za@http://november-9.local/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:8
$g@http://november-9.local/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:178
ja@http://november-9.local/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:73:111
Pa@http://november-9.local/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:157:212
Me@http://november-9.local/wp-content/plugins/gutenberg/vendor/react-dom.min.edd8b7a6.js:110:252
e@http://november-9.local/wp-content/plugins/gutenberg/build/data/index.min.js?ver=da4272fbc833ab25871c55f89400d555:1:19841
t@http://november-9.local/wp-content/plugins/gutenberg/build/data/index.min.js?ver=da4272fbc833ab25871c55f89400d555:1:19908
c/t.subscribe/o<@http://november-9.local/wp-content/plugins/gutenberg/build/data/index.min.js?ver=da4272fbc833ab25871c55f89400d555:1:14312
instantiate/b</<@http://november-9.local/wp-content/plugins/gutenberg/build/data/index.min.js?ver=da4272fbc833ab25871c55f89400d555:1:13434
y@http://november-9.local/wp-content/plugins/gutenberg/build/data/index.min.js?ver=da4272fbc833ab25871c55f89400d555:1:6847
instantiate/c</</</<@http://november-9.local/wp-content/plugins/gutenberg/build/data/index.min.js?ver=da4272fbc833ab25871c55f89400d555:1:10995
o/</</<@http://november-9.local/wp-content/plugins/gutenberg/build/redux-routine/index.min.js?ver=79381db76ebb53a195b3b8fa77d1a91b:1:8566
A/</<@http://november-9.local/wp-content/plugins/gutenberg/build/data/index.min.js?ver=da4272fbc833ab25871c55f89400d555:1:8792
P/</</<@http://november-9.local/wp-content/plugins/gutenberg/build/data/index.min.js?ver=da4272fbc833ab25871c55f89400d555:1:9138
get dispatch/<@http://november-9.local/wp-content/plugins/gutenberg/build/data/index.min.js?ver=da4272fbc833ab25871c55f89400d555:1:11310
Q/<@http://november-9.local/wp-content/plugins/gutenberg/build/core-data/index.min.js?ver=4ae78182423fd4ff98c52e9d7c293bfe:1:11870
```

**Comment by agapetry** [comment]
@skorasaurus I find that this error also occurs when running Revisions 2.6.3 along with the current Gutenberg plugin version.

**Comment by skorasaurus** [comment]
I've done some testing; I am able to reproduce it running Revisions 3.0 and Gutenberg 11.6; 
I am not able to reproduce it on Gutenberg 11.5.

**Comment by agapetry** [comment]
@skorasaurus A limitation of the workaround I implemented is that with the Gutenberg plugin active, the "Save Draft" button on the Edit Revision screen will not be re-captioned to "Update Revision"

**Comment by skorasaurus** [comment]
Thank you very much for the prompt response, fix, and release! ; It is functioning as expected in 3.0.1 as you described @agapetry

**Comment by skorasaurus** [comment]
One very minor regression to note in 3.0.x: (and I understand this is a nitpick, especially as a free user): 
once you submit a revision, that user is no longer is able to save any new edits to the revision. 

In Gutenberg 10.3 and 2.6.3; I was able to save additional edits to a post that already its revision submitted. 
as indicated below. 
![image](https://user-images.githubusercontent.com/955351/141522204-4c8c4794-8a2f-432a-a05e-f7e705eb1742.png)

In Gutenberg 10.3 and 3.0.1, the update revision prompt is not displayed.
