### ISSUE TITLE
Revisions 3 and the Events Calendar

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Revisions#529]
At the moment, Revisions 3 doesn't work with the Events Calendar

Original docs here:
https://publishpress.com/knowledge-base/revisions-events-calendar/

If you create a revision now, no Revisions buttons are shown, only "Publish"

<img width="1272" alt="Screen Shot 2021-11-15 at 4 20 37 PM" src="https://user-images.githubusercontent.com/3868028/141855444-af0a9076-8331-418e-ab77-de9b9da9710e.png">

**Comment by agapetry** [comment]
I see this after hitting "New Revision" from the Events list (running EC 5.10.1):

![image](https://user-images.githubusercontent.com/43488774/141857761-c9377b82-b38b-4de3-9f36-18d58ffb73f8.png)

**Comment by stevejburge** [comment]
@agapetry Ah, I was using Classic Editor. Maybe we tell people to just use Gutunberg here for now
