### ISSUE TITLE
Design update to frontend toolbar

### ISSUE THREAD

**Issue by htmgarcia** [publishpress/PublishPress-Revisions#548]
![Screen Shot 2021-11-17 at 12 58 28](https://user-images.githubusercontent.com/4999794/142264977-cd8aec00-4842-4b74-ba7c-4f8a678879e1.png)

**Comment by htmgarcia** [comment]
@stevejburge @agapetry starter proposal:
![Screen Shot 2021-11-25 at 15 06 33](https://user-images.githubusercontent.com/4999794/143499893-11a30a1c-aeb2-4ede-805d-f17bff46e8be.png)

**Comment by stevejburge** [comment]
@htmgarcia 100% a good idea. Yes, the Publish button should stand out clearly
