### ISSUE TITLE
Creating multiple revisions for one post

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Revisions#555]
> I'm having trouble accomplishing multiple future revisions for the same post. When I create one revision and schedule it for tomorrow, it seems fine. Then I edit the post again, and create New revision, when I go to edit the second revision, the edits don't ever trigger the 'submit revision'. 
> 
> Actually, I was able to accomplish this, however it just was unintuitive from the post edit screen. It required switching to the revision queue, and loading the second revision from the queue. Finally, it might be nice to be able to approve from the list in the queue, skipping the need to preview.

**Comment by agapetry** [comment]
@stevejburge Looking into this revealed a different bug: https://github.com/publishpress/PublishPress-Revisions/issues/745

But I haven't been able to reproduce the reported issue of subsequent revisions missing their Submit button in the revision editor.  Do you see that?
