### ISSUE TITLE
Error with Revisions Free and ACF

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Revisions#582]
> I have 3 custom fields on my Post post type. When I update a post or publish a new one, I have to click “Update” or “Publish” twice. The first click greys out the button for a short time, but the page doesn’t refresh and my changes won’t save. I have to click a second time for the save to process and the page to refresh. Disabling ACF or PublishPress resolves the issue.
> 
> It looks like this only happens with the Classic Editor plugin enabled.
> 

https://wordpress.org/support/topic/acf-publishpress-makes-me-have-to-click-twice-to-update-a-post/

![RH4fdrm](https://user-images.githubusercontent.com/3868028/145861706-f0fcff49-72b2-45ee-b52e-25ad9da87c13.png)

**Comment by agapetry** [comment]
@stevejburge We already have a fix ready to release for this.
