### ISSUE TITLE
Ensure all edits come through the revisions queue

### ISSUE THREAD

**Issue by petethomasmusique** [publishpress/PublishPress-Revisions#604]
Hi there. Thanks for the plugin!

My client wants to basically disable the `edit` button so that all pages/posts/CPTs etc have to go through the revisions queue. So, for example, on the page lists, when I hover over a page it would offer me the option `new` revision, not `edit`, or... the `edit` button defaults to a new revision.

Is this a built in feature? Or do I have to do some customisation?

Very many thanks.

Pete.

**Comment by stevejburge** [comment]
Hi @petethomasmusique 

Sorry, this is not possible with Revisions. It would require customisation
