### ISSUE TITLE
One very minor regression to note in 3.0.x: (and I understand this is a nitpick, especially as a free user):

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Revisions#614]
One very minor regression to note in 3.0.x: (and I understand this is a nitpick, especially as a free user): 
once you submit a revision, that user is no longer is able to save any new edits to the revision. 

In Gutenberg 10.3 and 2.6.3; I was able to save additional edits to a post that already its revision submitted. 
as indicated below. 
![image](https://user-images.githubusercontent.com/955351/141522204-4c8c4794-8a2f-432a-a05e-f7e705eb1742.png)

In Gutenberg 10.3 and 3.0.1 (also in 3.0.2.) the update revision prompt is not displayed. 

![image](https://user-images.githubusercontent.com/955351/141539647-4f5c4405-43d6-48cd-9ea0-8f21e6f2e6ff.png)

(Also reproducible in 3.0.6)

_Originally posted by @skorasaurus in https://github.com/publishpress/PublishPress-Revisions/issues/508#issuecomment-967459260_

**Comment by agapetry** [comment]
The Update Revision button (now captioned as "Save as pending") is only re-displayed after a further change to the revision content.
