### ISSUE TITLE
New translations and two possible bugs

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Revisions#689]
> Please, verify line ID 5, in the original string there's </span> missing in the plural and lines are both plural. It gave error on uploading and I fixed it online. 

> Also verify all the strings having singular/plural because some are only plural written and make confusion in translating or maybe I'm wrong.

[french.zip](https://github.com/publishpress/PublishPress-Revisions/files/8411875/french.zip)

[spanish.zip](https://github.com/publishpress/PublishPress-Revisions/files/8411890/spanish.zip)

[italian.zip](https://github.com/publishpress/PublishPress-Revisions/files/8411893/italian.zip)

**Comment by agapetry** [comment]
@stevejburge Is there an original message with more context?

**Comment by agapetry** [comment]
Closing because the new language files were included in 3.0.16.
