### ISSUE TITLE
Admin / Editor notifications not being sent

### ISSUE THREAD

**Issue by 7thcirclegit** [publishpress/PublishPress-Revisions#709]
Posted here based on this thread https://wordpress.org/support/topic/admin-editor-notifications-not-being-sent/

When someone submits a revision they receive an email saying they submitted a revision.

The admins and approvers do not get an email.

Email logs do not show a message being sent to anyone except the person submitting the revision.

Under notifications both options are set to “Always.
- Email Editors and Administrators when a Revision is submitted
- Email original Author when a Revision is submitted

The issue has been present since at least 3.0.13 but used to work without issue

PHP 7.4 and 8.0
WP 5.9.3
PublishPress Checklists v2.7.2
PublishPress Revisions 3.0.16
Email sent via Postmark using Fluent SMTP connected via API

**Comment by agapetry** [comment]
Closing as unconfirmed. This requires installation-specific troubleshooting.

**Comment by 7thcirclegit** [comment]
FYI, since @agapetry closed this without doing anything and I have no way to reopen it I have submitted a new ticket https://github.com/publishpress/PublishPress-Revisions/issues/751 and also reopened this on WP.org

**Comment by agapetry** [comment]
@7thcirclegit I did test this after your wordpress.org report.  As Steve said, we have not been able to recreate the issue on any of our installations.

If you would like to contribute to resolving it, feel free to send a login to a site that exhibits the issue: help@publishpress.com

**Comment by 7thcirclegit** [comment]
> @7thcirclegit I did test this after your wordpress.org report. As Steve said, we have not been able to recreate the issue on any of our installations.
> 
> If you would like to contribute to resolving it, feel free to send a login to a site that exhibits the issue: [help@publishpress.com](mailto:help@publishpress.com)

Site created and info sent
