### ISSUE TITLE
Indicate revisions along with title in pages/posts view

### ISSUE THREAD

**Issue by SJNBham** [publishpress/PublishPress-Revisions#71]
When a post is private or pending, the status is appended to the title in all posts/pages list views. It would be nice to have something like "Pending Revision" appended to posts that have active revisions. You can see a post has revisions by hovering over the title and seeing the Revision Queue link, but that requires you to hover over each post. 

![image](https://user-images.githubusercontent.com/11393597/80016476-05720a80-8488-11ea-8ac1-ab2d47107885.png)

**Comment by stevejburge** [comment]
@SJNBham Thanks - you've been putting forward some great ideas.

I'll cc @agapetry on this

**Comment by stevejburge** [comment]
solved in a recent release

**Comment by SJNBham** [comment]
Thanks you!

**Comment by stevejburge** [comment]
Thanks @SJNBham. Sorry, this was done a while ago, but I missed this during Github cleanups
