### ISSUE TITLE
NEW item Admin / Editor notifications not being sent

### ISSUE THREAD

**Issue by 7thcirclegit** [publishpress/PublishPress-Revisions#751]
Creating a new issue since someone was to lazy too test and felt the best resolution was to close the issue.

Posted here based on this thread https://wordpress.org/support/topic/admin-editor-notifications-not-being-sent/

When someone submits a revision they receive an email saying they submitted a revision.

The admins and approvers do not get an email.

Email logs do not show a message being sent to anyone except the person submitting the revision.

Under notifications both options are set to “Always.

Email Editors and Administrators when a Revision is submitted
Email original Author when a Revision is submitted
The issue has been present since at least 3.0.13 but used to work without issue

PHP 7.4 and 8.0
WP 5.9.3
PublishPress Checklists v2.7.2
PublishPress Revisions 3.0.16
Email sent via Postmark using Fluent SMTP connected via API

**Comment by stevejburge** [comment]
@7thcirclegit This an unconfirmed bug that no-one else has reported.

@agapetry Sorry, I did ask @7thcirclegit to open an issue. That's my fault.

Yes, this is really an issue that required Revisions Pro support.

**Comment by agapetry** [comment]
Closing as duplicate to #709
