### ISSUE TITLE
Respecting Polylang field values

### ISSUE THREAD

**Issue by dsakurai** [publishpress/PublishPress-Revisions#77]
Our page has custom fields to specify language settings since we use the Polylang plugin.

The PPR plugin does not retain the values in the fields when a revision page is created. See the attached image:
<img width="1057" alt="polylang" src="https://user-images.githubusercontent.com/16434308/81898928-9f932180-95f4-11ea-9f1d-ee224ea59ebf.png">

Could the field values somehow retained?

**Comment by stevejburge** [comment]
Thanks @dsakurai. I've tested can confirm this is not working.

Normally these meta fields are only supported in Revisions Pro, but they're not working there either. We'll get that fixed

**Comment by teid-bw** [comment]
Hello, I have a similar use case. Does this issue still exist on the pro version ?

**Comment by agapetry** [comment]
Polylang stores these settings as hidden taxonomy terms, not custom fields.  This requires some new integration development because Revisions does not normally interact with hidden taxonomies.  I'm working on it.

**Comment by agapetry** [comment]
@teid-bw @dsakurai  This issue is resolved in PublishPress Revisions 2.4.3-beta4.  The term storage correction applies to both the free and pro version.

https://github.com/publishpress/PublishPress-Revisions/releases/download/v2.4.3-beta4/revisionary_2.4.3-beta4.zip
