### ISSUE TITLE
Plugin "crippled" with DISABLE_WP_CRON defined.

### ISSUE THREAD

**Issue by rmpel** [publishpress/PublishPress-Revisions#786]
Hi there.

First off; thank you for the plugin, we use the Pro version and we love it, however, we have a small issue;

when DISABLE_WP_CRON is defined, the scheduling features are disabled. Normally, this would be fine, however;
1. if DISABLE_WP_CRON is `false`, this should not be the case. The check in the code is done only by `defined('DISABLE_WP_CRON')` instead of `defined('DISABLE_WP_CRON') && DISABLE_WP_CRON`
2. For large sites, running with DISABLE_WP_CRON true and calling the cron by CLI on server is much more efficient.

Therefore I'd like to request (and can provide a pull request for it) two changes
1. Fix the check so false positives are no longer an issue
2. add a filter on the check so we can bypass the check

If you are willing to apply these fixes, we'll provide a pull request for it.

Thank you for responding.

Remon.

**Comment by agapetry** [comment]
> For large sites, running with DISABLE_WP_CRON true and calling the cron by CLI on server is much more efficient.

So in your case, are you still working with events scheduled as with the wp-includes/cron.php functions, but handling the timed execution with custom code?

**Comment by rmpel** [comment]
Correct, using the wp-cli `wp cron event run --due-now`, all "waiting" tasks are executed, just as they would using the "regular" wp-cron, but no longer slow down the website.

(and thanks for the fast response :) )

**Comment by agapetry** [comment]
@rmpel Okay, that makes sense. Let me know if the "revisionary_wp_cron_disabled" filter I added in the last PR will work for you.
