### ISSUE TITLE
Revisions doesn't seem to use the domain/URL provided by preview_post_link filter in functions.php

### ISSUE THREAD

**Issue by leafling** [publishpress/PublishPress-Revisions#810]
In my functions.php file, I have a line to change the preview_post_link to an alternate domain
```
function get_preview_url( $preview_link ) {
	$length = strlen( get_option('home') );
	if( substr($preview_link, 0, $length) == get_option('home') ){
		$preview_link = ('https://preview.mydomain.com' . substr($preview_link, $length));
	}
	return $preview_link;
}
add_filter( 'preview_post_link', 'get_preview_url' );
```
The code above works in a barebones wordpress admin system and the preview links are properly adjusted with the new domain, but the preview links generated by the PublishPress-Revisions system don't seem to get run through the get_preview_url function and instead the revisions points preview links to the production site which is designed to not allow previews.

**Comment by agapetry** [comment]
@leafling What is the location of these links?

**Comment by leafling** [comment]
Our setup prevents previews on the **production** domain, https://www.mydomain.com
So we set up wordpress to preview via a **staging** domain, https://preview.mydomain.com
which is handled by the add_filter code and get_preview_url function which changes the preview_lost_link to use the https://**preview**.mydomain.com domain along with the preview path and params.

The Revisions plugin currently points the revision preview to a URL like this:
https://**www**.mydomain.com/slug/?preview=1&page_id=12345&post_type=page&nc=6bd6860e

While a regular wordpress admin preview link would utilize the get_preview_post_link function and point here:
https://**preview**.mydomain.com/slug/?preview=true

For most default installs these would be the same and the link that revisions uses would just work, but wordpress has the preview_post_link hook and the get_preview_post_link function, so it seems it should be used here as well.  Or offer some mechanism to similarly define the preview link for revisions.

https://developer.wordpress.org/reference/functions/get_preview_post_link/

Does this help?
