### ISSUE TITLE
Small notice bug with WooCommerce

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Revisions#83]
I’ve just updated to 2.3.6 and WordPress 5.4.2 and I get this two notices when listing products in WooCommerce in wp-admin:

Notice: Undefined property: stdClass::$pending-revision in …/wp-admin/includes/class-wp-posts-list-table.php on line 294

Notice: Undefined property: stdClass::$future-revision in …/wp-admin/includes/class-wp-posts-list-table.php on line 294

**Comment by cfaria** [comment]
Subscribed here. Thank you Steve!

**Comment by agapetry** [comment]
@stevejburge I can't replicate this now. It must have been fixed or we'd have many reports by now.
