### ISSUE TITLE
Error RvyPostEdit::author_ui()

### ISSUE THREAD

**Issue by celeryness** [publishpress/PublishPress-Revisions#850]
I have searched for any references to the function in question before raising a ticket.
PublishPress-Revisions Version 3.1.7
Wordpress 6.0.2
PHP version 8.0.22
Inside a docker container
I had just installed the plug-in in wp->admin->plug-ins, and I was editing a post in wp admin, which has a custom post type.

Full Error Message is:
PHP Fatal error:  Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, non-static method RvyPostEdit::author_ui() cannot be called statically in /app/wp-includes/class-wp-hook.php:307

I changed the source in post-edit_rvyp.php on line 184 to switch the function to static as a workaround so that I could continue.

**Comment by ThatStevensGuy** [comment]
We are also experiencing this, adding 'public static' to the function author_ui() on line 104 of revisionary/admin/post-edit-block-ui_rvy.php seemed to fix it.

PublishPress Revisions 3.1.7 
WordPress 6.0.3
PHP 8.0.24

**Comment by agapetry** [comment]
This was fixed by version 3.1.8, released 11/3/2022.
