### ISSUE TITLE
Incorrect filtering of $wp_post_statuses

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Revisions#851]
PP plugin is conflicting with mine for some users, in that its filters $wp_post_statuses and adds objects within the array for each post status. This is inconsistent with how WordPress does things, In a blank WordPress install the post statuses are all objects but everything blow that is an array or arrays.

Can you nake your plugin consistent with the standard WordPress way? The thread with more info is here:

https://wordpress.org/support/topic/several-plugin-conflicts-with-new-update/

Original thread: https://wordpress.org/support/topic/incorrect-filtering-of-wp_post_statuses/

**Comment by agapetry** [comment]
@rizaardiyanto1412 @stevejburge I don't think we should make the change he suggested. WordPress core treats the labels property as an object for post types and taxonomies. By extension, I think it's more consistent to treat a Post Status labels property the same way.
