### ISSUE TITLE
Missing strings in file .pot of Revisions PRO

### ISSUE THREAD

**Issue by wocmultimedia** [publishpress/PublishPress-Revisions#853]
Hi,

I'm checking the language folder for making the translations and some strings are missing  in the files .pot of Revisions PRO
Please, review or refresh it, because I saw that using the legacy from free version and checking the Pro.pot file some strings are not present in both Free and pro.pot. Besides the pro.pot has 377 strings while the localized languages have 391 strings.

Thanks,
Angelo

**Comment by agapetry** [comment]
https://github.com/publishpress/PublishPress-Revisions-Pro/commit/cec0fffd98ea4aac60e92b1906379e717720f8b7
