### ISSUE TITLE
rvy_glance_pending() should accept and return an array

### ISSUE THREAD

**Issue by paulgibbs** [publishpress/PublishPress-Revisions#86]
The WordPress action "dashboard_glance_items" is passed an array and expects an array to be returned from its callbacks.

The function `rvy_glance_pending()` does not have the parameter declared, and does not return it.
Also, the HTML structure printed by this handler should be returned rather than printed directly to the screen.

**Comment by colevalleygirl** [comment]
We're also suffering from this issue, which is preventing the site Dashboard form working.

**Comment by EvanK** [comment]
We are also having this issue.

Our current workaround is to add any `dashboard_glance_items ` actions/filters at a higher than default priority, ensuring they run _after_ this one. It makes for an ugly visual, but hey it works.
