### ISSUE TITLE
Add warnings if Revisions are disabled globally or per post type?

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Revisions#862]
We ran into a situation where a lot of post types were available to be selected in PublishPress Revisions, but they had the revisions feature disabled

**Comment by stevejburge** [comment]
@agapetry Sorry, I should have explained this better. Here's WooCommerce. Most of these post types don't have revisions:
<img width="454" alt="Screenshot 2023-03-23 at 2 04 11 PM" src="https://user-images.githubusercontent.com/3868028/227304362-1c02fb9d-f9f0-49f0-8e04-4ca240d668aa.png">

**Comment by stevejburge** [comment]
Related:

> We struggled with it working correctly on MultiSite using WPEngine, which uncovered a flaw. WPEngine disables the core page revision functionality by default, which your plugin should likely add a check and alert the user IF that is disabled since it appears to keep the plugin from working properly.

**Comment by agapetry** [comment]
@stevejburge The caption on the Post Types tab was updated to clarify that those checkboxes pertain to revision submission, which does not rely on WordPress revisions being enabled:

![image](https://github.com/publishpress/PublishPress-Revisions/assets/43488774/6e29a75a-1248-4092-8c1c-c5f7ee054eef)

At the same time, the post type dropdown on the Revision Archive screen (as originally introduced) includes only post types that have standard revisions enabled. 

https://github.com/publishpress/PublishPress-Revisions/commit/8a73b16441e4e175673ad9f41422e19444036f3d
