### ISSUE TITLE
Revision Translation Updates ES-FR-IT_January 2023

### ISSUE THREAD

**Issue by wocmultimedia** [publishpress/PublishPress-Revisions#900]
Hi,
Here's Revision Translation Updates ES-FR-IT_January 2023. Please, add to languages folder.
[Revisionary_Translation_Updates_ES-FR-IT_January2023.zip](https://github.com/publishpress/PublishPress-Revisions/files/10394438/Revisionary_Translation_Updates_ES-FR-IT_January2023.zip)

Thanks,
Angelo

**Comment by agapetry** [comment]
https://github.com/publishpress/PublishPress-Revisions/commit/82a337cd07dd4deb659c4b45a122d45e7d3edb4d

https://github.com/publishpress/PublishPress-Revisions-Pro/commit/cec0fffd98ea4aac60e92b1906379e717720f8b7
