### ISSUE TITLE
PRO languages folder have the same po/mo files of FREE languages folder

### ISSUE THREAD

**Issue by wocmultimedia** [publishpress/PublishPress-Revisions#901]
Hi Steve,

I just made a check and the PRO languages folder have the same po/mo files of FREE languages folder. Is it correct?
No file pot is inside the PRO languages folder.
Please, let me know about it.

Thanks
Angelo

**Comment by agapetry** [comment]
@wocmultimedia The issue is noted, will likely be corrected in 3.1.12
