### ISSUE TITLE
Has Revisions without changes

### ISSUE THREAD

**Issue by rizaardiyanto1412** [publishpress/PublishPress-Revisions#902]
When a user clicks New Revision and goes into the doc, but makes no changes and clicks out without saving a draft etc, it still sets the status as 'in revision'

Expected behavior: this is set to not happen, as it is confusing for other staff who see this status even though the full admin see it as 'not submitted'.

Ticket: https://secure.helpscout.net/conversation/2137748633/175649?folderId=6932143

**Comment by agapetry** [comment]
Sorry, but "New Revision" actually creates a revision. This is a necessary change from older versions of the plugin, which did not create the revision until after editing is done. The revision can be deleted to clear the "Has Revision" flag.

**Comment by JoshJourney** [comment]
@agapetry I understand that the new approach requires creating a new revision regardless to whether there is any content inside of it. What if upon exiting the new revision there was an event that checks if the revision is blank? If it's blank, the revision could automatically be deleted. After all no one benefits from blank content that was not intentionally submitted an only adds spam to the queue (unintentionally).
