### ISSUE TITLE
Republished posts messes with CSS added by Elementor

### ISSUE THREAD

**Issue by shreyasikhar** [publishpress/PublishPress-Revisions#932]
After republishing the post, some of the CSS doesn’t get rendered on the frontend, while this CSS renders correctly on the elementor editor.

I have found that CSS with selectors having class `.elementor-{post_id}` has some issues during republishing.

This CSS issue can be fixed by manually going to elementor editor of the scheduled post (once republished) and clicking [Update](https://prnt.sc/xEGgrSUXLTfq), ideally this should not be required with scheduled posts.

Please check this issue, thanks.

### Steps to reproduce:
1. Go to posts screen from WordPress backend
2. Hover on any post, then click on `New Revision`.
3. Then click on `Edit with Elementor`, make new changes and click `Update`
4. Go back to Gutenberg Editor and select the scheduled time and click on `Submit`.
5. Go to `Revisions` from WordPress backend menu, then click on edit on that revision, then click on `Approve Revision`
6. Wait for scheduled time to pass, and then check on frontend.

**Comment by stevejburge** [comment]
Hi @shreyasikhar. The Free version of Revisions doesn't support Elementor.

If you're using the Pro version, which does support Elementor, please open a support ticket on our site.
