### ISSUE TITLE
[Beaver Builder] Redirect Loop 

### ISSUE THREAD

**Issue by Pross** [publishpress/PublishPress-Revisions#982]
In new 2.7 version of Beaver Builder a new iframe responsive editing mode was added with a slight url change:
`<url>/?fl_builder&fl_builder_ui` The second variable fl_builder_ui tells BB to load the new reposnsive UI. This causes your edit url filter to cause a redirect loop with Beaver Builder.

The new responsive UI can be disabled in the advanced settings which is what your customer ended up doing but it isnt an ideal workaround.

**Comment by stevejburge** [comment]
Hi @Pross 
Are you using the Pro version of Revisions here? The Free version doesn't support Beaver Builder

**Comment by Pross** [comment]
Our mutual customer is yes, he provided me with a copy. I have a small patch for you shall I add it here?

**Comment by stevejburge** [comment]
@Pross Sure, we're open to PRs

**Comment by Pross** [comment]
Well I couldnt open a PR for this as I dont have access to the pro code here. But here is the diff for that file
```
diff --git a/includes-pro/compat/beaver-builder.php b/includes-pro/compat/beaver-builder.php
index d89a453..63e1705 100644
--- a/includes-pro/compat/beaver-builder.php
+++ b/includes-pro/compat/beaver-builder.php
@@ -45,11 +45,15 @@ class RevisionaryBeaverBuilder
 
 		$scheme = ( isset( $matches[1] ) ) ? $matches[1] : false;
 
-		$url = set_url_scheme( add_query_arg( 'fl_builder', '', rvy_preview_url($post) ), $scheme );
+		$url = set_url_scheme( add_query_arg( $this->getbbargs(), rvy_preview_url($post) ), $scheme );
 
 		return $url;
 	}
 
+	function getbbargs() {
+		return method_exists( 'FLBuilderUIIFrame', 'is_enabled' ) && FLBuilderUIIFrame::is_enabled() ? ['fl_builder' => '', 'fl_builder_ui' => ''] : ['fl_builder' => ''];
+	}
+
 	function fltPermalink($url, $post) {
 		static $busy;
 
@@ -189,7 +193,7 @@ class RevisionaryBeaverBuilder
 
 	function fltCreateRevisionRedirect($url, $post_id) {
         if (!empty($_REQUEST['front']) && !defined('PP_REVISIONS_BEAVER_BUILDER_NO_REDIRECT')) {
-			$url = add_query_arg(['fl_builder' => ''], rvy_preview_url($post_id));
+			$url = add_query_arg( $this->getbbargs(), rvy_preview_url($post_id));
         }
 
         return $url;
@@ -200,7 +204,7 @@ class RevisionaryBeaverBuilder
 		
         $actions['beaver'] = sprintf(
             '<a href="%1$s" class="" title="%2$s" aria-label="%2$s">%3$s</a>',
-            add_query_arg(['fl_builder' => ''], rvy_preview_url($post->ID)),
+            add_query_arg( $this->getbbargs(), rvy_preview_url($post->ID)),
             $bb,
             $bb
         );

```

**Comment by stevejburge** [comment]
Thanks @Pross

**Comment by wellscollege2023** [comment]
Hi @stevejburge. Popping in to the convo. We are the client. I'll follow up with you via a ticket. Happy to help test a fix. Thanks so much!

**Comment by wellscollege2023** [comment]
Quick update: Kevin from PP sent me v3.2.1-rc2 of Revisions Pro to test.  I can confirm that the redirect issue is still occurring. If I switch off the new responsive UI feature in BB, it does work fine.  When that new feature is on - the redirect issue returns.
